version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - ${PGPORT}:5432
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
